---
abstract: 'Universally Unique IDentifier (UUID) Generator'
author:
  - 'ITO Nobuaki <banb@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: UUID-Generator-PurePerl
no_index:
  directory:
    - inc
    - t
recommends:
  Digest::MD5: 2.2
  Digest::SHA: 5.32
requires:
  Carp: 0
  Digest: 1
  Time::HiRes: 1.2
  UUID::Object: 0.01
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
